name: CI

on:
  push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
  
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Build Gatsby
        run: npm run build
        env:
          CI: true
  
      - name: Archive production artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public